### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by Bren2010**
This should give you the same GitHub pages website as mls-protocol

### CODE REVIEW

**Comment by Bren2010** [comment]
Yeah go for it

**Comment by beurdouche** [comment]
🙇‍♂️

**Comment by beurdouche** [comment]
Woops, something went wrong...

**Comment by Bren2010** [comment]
Someone with push to this repo just needs to run "make -f lib/setup.mk setup-ghpages"

**Comment by beurdouche** [comment]
Ack, don’t have a computer, but I’ll do this asap. Thanks :)

**Pull request merged**
